name: ifc
channels:
  - conda-forge
  - defaults
dependencies:
  - boost-cpp=1.74.0=h5b4e17d_5
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2021.10.8=h5b45459_0
  - fontconfig=2.13.1=h1989441_1005
  - freetype=2.10.4=h546665d_1
  - ifcopenshell=v0.6.0=py38h11be7c3_3
  - libiconv=1.16=he774522_0
  - libpng=1.6.37=h1d00b33_2
  - libxml2=2.9.12=hf5bbc77_1
  - libzlib=1.2.11=h8ffe710_1013
  - lz4-c=1.9.3=h8ffe710_1
  - occt=7.4.0=h823b557_3
  - openssl=3.0.0=h8ffe710_2
  - pip=21.3.1=pyhd8ed1ab_0
  - python=3.8.12=h900ac77_2_cpython
  - python_abi=3.8=2_cp38
  - setuptools=59.4.0=py38haa244fe_0
  - sqlite=3.37.0=h8ffe710_0
  - tbb=2020.2=h2d74725_4
  - ucrt=10.0.20348.0=h57928b3_0
  - vc=14.2=hb210afc_5
  - vs2015_runtime=14.29.30037=h902a5da_5
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=h62dcd97_1
  - zlib=1.2.11=h8ffe710_1013
  - zstd=1.5.0=h6255e5f_0
  - pip:
    - anyio==3.4.0
    - argon2-cffi==21.1.0
    - attrs==21.2.0
    - babel==2.9.1
    - backcall==0.2.0
    - bleach==4.1.0
    - certifi==2021.10.8
    - cffi==1.15.0
    - charset-normalizer==2.0.8
    - colorama==0.4.4
    - debugpy==1.5.1
    - decorator==5.1.0
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - entrypoints==0.3
    - idna==3.3
    - importlib-resources==5.4.0
    - ipykernel==6.5.1
    - ipython==7.30.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.1
    - jinja2==3.0.3
    - json5==0.9.6
    - jsonschema==4.2.1
    - jupyter-client==7.1.0
    - jupyter-core==4.9.1
    - jupyter-packaging==0.11.1
    - jupyter-server==1.12.1
    - jupyterlab==3.2.4
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.8.2
    - jupyterlab-widgets==1.0.2
    - lark==1.0.0
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclassic==0.3.4
    - nbclient==0.5.9
    - nbconvert==6.3.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.6
    - numpy==1.21.4
    - open3d==0.13.0
    - packaging==21.3
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pickleshare==0.7.5
    - prometheus-client==0.12.0
    - prompt-toolkit==3.0.23
    - pycparser==2.21
    - pygments==2.10.0
    - pyparsing==3.0.6
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pywin32==302
    - pywinpty==1.1.6
    - pyzmq==22.3.0
    - requests==2.26.0
    - send2trash==1.8.0
    - six==1.16.0
    - sniffio==1.2.0
    - terminado==0.12.1
    - testpath==0.5.0
    - tomlkit==0.7.2
    - tornado==6.1
    - traitlets==5.1.1
    - urllib3==1.26.7
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.1
    - widgetsnbextension==3.5.2
    - zipp==3.6.0
prefix: C:\Users\SamDeGeyter\anaconda3\envs\ifc
